import axiosInstance from './axios';

export const getAdminDashboard = () => axiosInstance.get('/admin/dashboard');
export const getAllUsers = (params) => axiosInstance.get('/admin/users', { params });
export const getUserById = (id) => axiosInstance.get(`/admin/users/${id}`);
export const deactivateUser = (id) => axiosInstance.patch(`/admin/users/${id}/deactivate`);
export const reactivateUser = (id) => axiosInstance.patch(`/admin/users/${id}/reactivate`);
export const getAllPets = (params) => axiosInstance.get('/admin/pets', { params });
export const getPendingVets = () => axiosInstance.get('/admin/vets/pending');
export const getAllAdminVets = (params) => axiosInstance.get('/admin/vets', { params });
export const approveVet = (id) => axiosInstance.patch(`/admin/vets/${id}/approve`);
export const rejectVet = (id, reason) => axiosInstance.patch(`/admin/vets/${id}/reject`, { reason });
export const getPendingArticles = () => axiosInstance.get('/admin/articles/pending');
export const getAllArticles = (params) => axiosInstance.get('/admin/articles', { params });
export const publishArticle = (id) => axiosInstance.patch(`/admin/articles/${id}/publish`);
export const rejectArticle = (id, reason) => axiosInstance.patch(`/admin/articles/${id}/reject`, { reason });
export const getReportedPosts = () => axiosInstance.get('/admin/forum/reported');
export const getAllForumPosts = (params) => axiosInstance.get('/admin/forum', { params });
export const removePost = (id) => axiosInstance.delete(`/admin/forum/${id}`);
export const dismissPostReport = (id) => axiosInstance.patch(`/admin/forum/${id}/dismiss-report`);
export const pinPost = (id) => axiosInstance.patch(`/admin/forum/${id}/pin`);
export const getPendingProducts = () => axiosInstance.get('/admin/products/pending');
export const getAllProducts = (params) => axiosInstance.get('/admin/products', { params });
export const approveProduct = (id) => axiosInstance.patch(`/admin/products/${id}/approve`);
export const rejectProduct = (id, reason) => axiosInstance.patch(`/admin/products/${id}/reject`, { reason });
export const getAllOrders = (params) => axiosInstance.get('/admin/orders', { params });